//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WineCore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.WeatherDays = new HashSet<WeatherDay>();
            this.CityVintages = new HashSet<CityVintage>();
        }
    
        public int CityId { get; set; }
        public string City1 { get; set; }
        public int RegionId { get; set; }
        public string WundergroundEndpoint { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<WeatherDay> WeatherDays { get; set; }
        public virtual ICollection<CityVintage> CityVintages { get; set; }
    }
}
