//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WineCore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityVintage
    {
        public int CityVintageId { get; set; }
        public int CityId { get; set; }
        public int VintageId { get; set; }
        public double HeatingDays { get; set; }
    
        public virtual City City { get; set; }
        public virtual Vintage Vintage { get; set; }
    }
}
