//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WineCore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vintage
    {
        public Vintage()
        {
            this.WeatherDays = new HashSet<WeatherDay>();
        }
    
        public int VintageId { get; set; }
        public int Year { get; set; }
        public int RegionId { get; set; }
        public int ParkerScore { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<WeatherDay> WeatherDays { get; set; }
    }
}
