//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WineCore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherDay
    {
        public int WeatherDayId { get; set; }
        public System.DateTime Date { get; set; }
        public int CityId { get; set; }
        public double HighTemperature { get; set; }
        public double LowTemperature { get; set; }
        public double Precipitation { get; set; }
        public Nullable<double> MeanTemperature { get; set; }
        public Nullable<double> DegreeDays { get; set; }
    }
}
